### PR TITLE
Fix broadcast issues + misc items

### LINKED ISSUE #6: ActionCable shouldn't broadcast to ALL office hours

### PR DESCRIPTION
**Pull request by hmontero1205**
Closes #6 

@emesterhazy I reverted your form validation for enqueuing because it causes the page to be refreshed. I manually replicated the validation using JS.

### CODE REVIEW

File: app/assets/javascripts/channels/office_hour.js [hunk 1]
```diff
@@ -16,6 +16,10 @@ App.oh = App.cable.subscriptions.create("OfficeHourChannel", {
 
   received: function(data) {
     // Called when there's incoming data on the websocket for this channel
+    ohID = $("#oh-input").val()  
+    if (data["ohID"] != ohID) {
```
Comment (emesterhazy) [inline app/assets/javascripts/channels/office_hour.js:20]: nice

**Review by emesterhazy — APPROVED** [review]
Looks good to me
